# Generated by Django 4.2 on 2024-03-31 18:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dept_name', models.CharField(max_length=100)),
                ('owner', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='LegalInstrument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('requires_change', models.BooleanField(default=False)),
                ('change_text', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_name', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('manual', 'Manual'), ('digital', 'Digital')], max_length=20)),
                ('timeline', models.CharField(blank=True, choices=[('Y1', 'Y1-2023/24'), ('Y2', 'Y2-2024/25'), ('Y3', 'Y3-2025/26'), ('Y4', 'Y4-2026/27')], max_length=2, null=True)),
                ('ecitizen', models.CharField(choices=[('yes', 'Yes'), ('no', 'No')], max_length=3)),
                ('enhancement', models.CharField(choices=[('yes', 'Yes'), ('no', 'No')], max_length=3)),
                ('dept', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Api.department')),
                ('legal_instrument', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Api.legalinstrument')),
            ],
        ),
    ]
