# Generated by Django 4.2 on 2024-04-30 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='timeline',
            field=models.CharField(blank=True, choices=[('none', 'None'), ('Y1-2023/24', 'Y1-2023/24'), ('Y2-2024/25', 'Y2-2024/25'), ('Y3-2025/26', 'Y3-2025/26'), ('Y4-2026/27', 'Y4-2026/27')], max_length=20, null=True),
        ),
    ]
