# Generated by Django 4.2 on 2024-04-30 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Api', '0003_alter_service_ecitizen_alter_service_enhancement_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='ecitizen',
            field=models.CharField(choices=[('yes', 'Yes'), ('No', 'No')], max_length=3),
        ),
        migrations.AlterField(
            model_name='service',
            name='enhancement',
            field=models.CharField(choices=[('yes', 'Yes'), ('No', 'No')], max_length=3),
        ),
    ]
