# Generated by Django 4.2 on 2024-04-30 16:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Api', '0004_alter_service_ecitizen_alter_service_enhancement'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='legal_instrument',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Api.legalinstrument'),
        ),
    ]
